### ISSUE TITLE
Operator to denote simple type arrays

### ISSUE THREAD

**Issue by faniereynders** [expandoco/expando-docs#7]
Currently only complex types are supported as arrays by using the astrix (*) operator:

```
string,tags:string*3
```

Produces:

```
{
   "string": "abc",
   "tags":
   [
      {
         "string":"abc"
      },
      {
         "string":"abc"
      },
      {
         "string":"abc"
      }
   ]
}
```

We need a way to also produce simple type arrays like this:

```
{
   "string": "abc",
   "tags":
   [
      "abc",
      "abc",
      "abc"
   ]
}
```

Any suggestions to the syntax?

**Comment by rvdvyver** [comment]
@faniereynders we should actually introduce a specific operator for simple type arrays and leave the `*` operator for multiplication:

```
string*3
```

Produces:

```
{
   [
      {
         "string":"abc"
      },
      {
         "string":"def"
      },
      {
         "string":"ghi"
      }
   ]
}
```

The `@` operator could denote a simple type array in this case:

```
string@3
```

Produces:

```
{
   "string":
   [
      "abc",
      "def",
      "hij"
   ]
}
```

Your thoughts?

**Comment by faniereynders** [comment]
Great idea @rvdvyver!

**Comment by rvdvyver** [comment]
Yes - I agree we need to add the @ operator for defining arrays.
